content = open('module/pyrogram_extension.py', 'r').read()

# 修正后的 old_loop — 匹配实际文件缩进（8空格基础）
old_loop = (
    '        for j, msg in enumerate(batch):\n'
    '            cap = combined if j == 0 else ""\n'
    '            if msg.video:\n'
    '                media_list.append(\n'
    '                    pyrogram.types.InputMediaVideo(\n'
    '                        media=msg.video.file_id, caption=cap))\n'
    '            elif msg.photo:\n'
    '                media_list.append(\n'
    '                    pyrogram.types.InputMediaPhoto(\n'
    '                        media=msg.photo.file_id))\n'
    '            elif msg.document:\n'
    '                media_list.append(\n'
    '                    pyrogram.types.InputMediaDocument(\n'
    '                        media=msg.document.file_id))\n'
    '        await node.upload_user.send_media_group(\n'
    '            node.upload_telegram_chat_id, media_list,\n'
    '            message_thread_id=node.topic_id)'
)

new_loop = (
    '        for j, msg in enumerate(batch):\n'
    '            cap = combined if j == 0 else ""\n'
    '            if msg.video:\n'
    '                try:\n'
    '                    fresh = await client.get_messages(node.chat_id, msg.id)\n'
    '                    if fresh and fresh.video:\n'
    '                        msg = fresh\n'
    '                except Exception:\n'
    '                    pass\n'
    '                try:\n'
    '                    path = await asyncio.wait_for(\n'
    '                        client.download_media(msg.video,\n'
    '                            progress=update_upload_stat,\n'
    '                            progress_args=(msg.id, os.path.basename(str(msg.video.file_id)),\n'
    '                                time.time(), node, client)),\n'
    '                        timeout=300)\n'
    '                    temp_files.append(str(path))\n'
    '                    if _needs_transcode(str(path)):\n'
    '                        logger.info("Transcoding msg %s to H.264...", msg.id)\n'
    '                        fixed = _transcode_video(str(path))\n'
    '                        if fixed:\n'
    '                            temp_files.append(fixed)\n'
    '                            path = fixed\n'
    '                            logger.info("Transcode msg %s complete", msg.id)\n'
    '                    media_list.append(\n'
    '                        pyrogram.types.InputMediaVideo(\n'
    '                            media=str(path), caption=cap,\n'
    '                            width=msg.video.width,\n'
    '                            height=msg.video.height,\n'
    '                            duration=msg.video.duration,\n'
    '                            supports_streaming=True))\n'
    '                    node.stat_forward(ForwardStatus.SuccessForward)\n'
    '                    await report_bot_status(node.bot, node, immediate_reply=True)\n'
    '                except asyncio.TimeoutError:\n'
    '                    logger.warning("Download timeout for msg %s, skipping", msg.id)\n'
    '                    node.stat_forward(ForwardStatus.FailedForward)\n'
    '                    await report_bot_status(node.bot, node, immediate_reply=True)\n'
    '                    continue\n'
    '                except Exception as e:\n'
    '                    logger.error("Download failed for msg %s: %s", msg.id, e)\n'
    '                    node.stat_forward(ForwardStatus.FailedForward)\n'
    '                    await report_bot_status(node.bot, node, immediate_reply=True)\n'
    '                    continue\n'
    '            elif msg.photo:\n'
    '                media_list.append(\n'
    '                    pyrogram.types.InputMediaPhoto(\n'
    '                        media=msg.photo.file_id))\n'
    '                node.stat_forward(ForwardStatus.SuccessForward)\n'
    '            elif msg.document:\n'
    '                try:\n'
    '                    fresh = await client.get_messages(node.chat_id, msg.id)\n'
    '                    if fresh and fresh.document:\n'
    '                        msg = fresh\n'
    '                except Exception:\n'
    '                    pass\n'
    '                try:\n'
    '                    path = await asyncio.wait_for(\n'
    '                        client.download_media(msg.document,\n'
    '                            progress=update_upload_stat,\n'
    '                            progress_args=(msg.id, os.path.basename(str(msg.document.file_id)),\n'
    '                                time.time(), node, client)),\n'
    '                        timeout=300)\n'
    '                    temp_files.append(str(path))\n'
    '                    media_list.append(\n'
    '                        pyrogram.types.InputMediaDocument(\n'
    '                            media=str(path), caption=cap,\n'
    '                            attributes=msg.document.attributes))\n'
    '                    node.stat_forward(ForwardStatus.SuccessForward)\n'
    '                    await report_bot_status(node.bot, node, immediate_reply=True)\n'
    '                except asyncio.TimeoutError:\n'
    '                    logger.warning("Download timeout for msg %s, skipping", msg.id)\n'
    '                    node.stat_forward(ForwardStatus.FailedForward)\n'
    '                    await report_bot_status(node.bot, node, immediate_reply=True)\n'
    '                    continue\n'
    '                except Exception as e:\n'
    '                    logger.error("Download failed for msg %s: %s", msg.id, e)\n'
    '                    node.stat_forward(ForwardStatus.FailedForward)\n'
    '                    await report_bot_status(node.bot, node, immediate_reply=True)\n'
    '                    continue\n'
    '        if media_list:\n'
    '            await node.upload_user.send_media_group(\n'
    '                node.upload_telegram_chat_id, media_list,\n'
    '                message_thread_id=node.topic_id)'
)

if old_loop in content:
    content = content.replace(old_loop, new_loop, 1)
    print("Part 1: _flush_album_mode loop REPLACED")
else:
    print("Part 1: old_loop NOT FOUND - printing actual code for debug")
    for i, line in enumerate(content.split('\n')):
        if 'for j, msg in enumerate(batch):' in line:
            for j in range(i, min(i+15, len(content.split('\n')))):
                print(f"  {j+1}: {repr(content.split(chr(10))[j])}")
            break

open('module/pyrogram_extension.py', 'w').write(content)
print('DONE')
